### ISSUE TITLE
pose_sensor2car标定的是车体还是gps？

### ISSUE THREAD

**Issue by Tausc** [OpenCalib/SensorX2car#3]
你好，请问pose_sensor2car中，最终的标定结果是imu到gps东北天坐标系的还是imu到车体坐标系的？

**Comment by Tausc** [comment]
以及，请问能否说明一下novatel-utm.csv中的数据格式？
比如其中的xyz是基于什么坐标系测量得到的呢？谢谢！

**Comment by sisyphus-99** [comment]
你好，是imu到车体坐标系的yaw角。
novatel-utm.csv中，xyz的坐标原点位于本初子午线与赤道交点，x轴方向朝东，y轴方向朝北，z轴方向朝天，ve,vn,vu分别是朝东，朝北，朝天的速度，roll，pitch，yaw为绕x,y,z轴的角度。

**Comment by Tausc** [comment]
那么请问imu的rpy是基于什么坐标系又如何获得的呢……在直线行驶的情况下，不考虑噪声等因素，imu积分得到的yaw角不应该是恒等于0的吗？

**Comment by sisyphus-99** [comment]
IMU的rpy也是基于上述UTM坐标系：原点在经纬度(0°,0°)，x轴方向朝东，y轴方向朝北
是指novatel-xxx.csv中的yaw角吗？由于是IMU体坐标系相对于UTM坐标系的角度，所以不会恒等于0

**Comment by Tausc** [comment]
可是请问imu相对于utm的角度是如何获得的呢？

**Comment by sisyphus-99** [comment]
GNSS/INS（比如此数据用的Novatel）可以提供这个输出，原理上大概是INS在初始化时可以根据当前位置，重力方向获得IMU体坐标系相对于世界坐标系方向的姿态，而IMU角速度，加速度积分可得到后续时刻相对于初始状态的姿态变化

**Comment by Tausc** [comment]
感谢您的回复！我还有两个问题：

1. 请问根据“重力方向获得IMU体坐标系相对于世界坐标系方向的姿态”这一部分，是如何进行的呢？理论上已知重力能恢复出roll、pitch相对世界坐标系的角度，但yaw角如何获得呢？请问是否能提供一下将原始的imu角速度和加速度数据处理成算法所需格式的相关工具？
2. 我阅读了SensorX2car: Sensors-to-car calibration for autonomous driving in road scenarios这篇论文，在E. Pose-sensor Calibration这一部分，论文中自由行驶只能标定出yaw角，请问代码中的rp角是怎么计算得到的呢？

非常感谢！！！

**Comment by sisyphus-99** [comment]
1. 我们使用Novatel直接输出了这个rpy角度，具体算法涉及GNSS/INS融合定位，要参考Novatel相关技术文档，这一部分不在我们的工作中。原理上获得yaw角一种方法是运动初始化，在初始化阶段使传感器朝向前正方向移动，根据GNSS定位和速度获得初始yaw角。
2. 代码中的rp角用的是和yaw角类似的标定方法，如标定pitch角时拟合yz平面运动轨迹，但由于车辆在z方向的运动很小，rp角度本身很小，因此估计不够可靠，实际上只做yaw角估计

**Comment by Tausc** [comment]
我明白了，非常感谢您的耐心回复！
