### ISSUE TITLE
how  to get euler angle from camera2car

### ISSUE THREAD

**Issue by yangsuhui** [OpenCalib/SensorX2car#4]
Great job; but how can I get three eular angle and ratotion matrixs( camera extrincs) from VP and horizon line?
Thank you very much!

**Comment by sisyphus-99** [comment]
We uploaded a new file, converting VP and HL to the rotation matrix, please check it.
https://github.com/OpenCalib/SensorX2car/blob/main/camera2car/auto_calib/vphl2R.py
