### ISSUE TITLE
core dump

### ISSUE THREAD

**Issue by bigplanestar** [OpenCalib/SensorX2car#5]
use example date ,run the lidar2car demo ,The following situations occur：

Using 60 frames from 296 lidar frames in total.
cost time: 27.79s
Final result:
roll = 0.603595 degree
pitch = 0.747207 degree
z = 2.09129 m
terminate called after throwing an instance of 'std::runtime_error'
  what():  Call to save() failed.
Aborted (core dumped)

**Comment by junji-code** [comment]
Hello, same happened to me, you know why its happening?

**Comment by scw318** [comment]
Uncommenting the plt::backend("Agg") of yawCalib.cpp works for me. I don't know if that's the problem.

**Comment by wangxianggang1997** [comment]
> use example date ,run the lidar2car demo ,The following situations occur：
> 
> Using 60 frames from 296 lidar frames in total. cost time: 27.79s Final result: roll = 0.603595 degree pitch = 0.747207 degree z = 2.09129 m terminate called after throwing an instance of 'std::runtime_error' what(): Call to save() failed. Aborted (core dumped)

could you please tell me how to solve this ? thank you!
